name: pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo branch main
        uses: actions/checkout@v4
        with:
          ref: "main"
          token: "${{ secrets.REPO_DATA_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ghostscript
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build

      - name: Run workflows/pipeline.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          export PYTHONPATH="$PYTHONPATH:./src"

          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          python workflows/pipeline.py "100"

      - name: Push
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "🤖 $(date '+%Y-%m-%d-%H%M') - pipeline.yml"

          git pull --rebase origin main
          git push origin main
